// AUTO-GENERATED by scripts/build-emoticons.mjs — do not edit by hand.
export const EMOTICON_SETS = [{"id":"harty","name":"하트콩","animated":true},{"id":"bear","name":"러비베어","animated":true},{"id":"bunny","name":"토순이","animated":true},{"id":"mochi","name":"콩떡","animated":false},{"id":"nyang","name":"냥이","animated":false},{"id":"chick","name":"삐약이","animated":false},{"id":"tofu","name":"두부","animated":false},{"id":"berry","name":"딸기","animated":false}] as const;

export const EMOTICON_EMOTIONS = [{"id":"love","label":"사랑해"},{"id":"hearteyes","label":"심쿵"},{"id":"wink","label":"윙크"},{"id":"happy","label":"신나"},{"id":"lol","label":"ㅋㅋㅋ"},{"id":"sad","label":"슬퍼"},{"id":"cry","label":"엉엉"},{"id":"angry","label":"화나"},{"id":"pout","label":"삐짐"},{"id":"sleepy","label":"졸려"},{"id":"surprised","label":"헉"},{"id":"shy","label":"부끄"},{"id":"tongue","label":"메롱"},{"id":"ok","label":"오케이"},{"id":"good","label":"최고"},{"id":"clap","label":"짝짝"},{"id":"hungry","label":"배고파"},{"id":"sick","label":"아파"},{"id":"party","label":"축하해"},{"id":"kiss","label":"뽀뽀"}] as const;

export function emoticonSrc(setId: string, emoId: string): string {
  return `/emoticons/${setId}/${emoId}.svg`;
}

/** Matches a message that is exactly one emoticon: [[emo:set:id]] */
export const EMO_RE = /^\[\[emo:([a-z]+):([a-z]+)\]\]$/;
